# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Task.create([
    { title: "Apple", content:"Lorem ipsum" },
    { title: "Watermelon", content:"Lorem ipsum" },
    { title: "Orange", content:"Lorem ipsum" },
    { title: "Pear", content:"Lorem ipsum" },
    { title: "Cherry", content:"Lorem ipsum" },
    { title: "Strawberry", content:"Lorem ipsum" },
    { title: "Nectarine", content:"Lorem ipsum" },
    { title: "Grape", content:"Lorem ipsum" },
    { title: "Mango", content:"Lorem ipsum" },
    { title: "Blueberry", content:"Lorem ipsum" },
    { title: "Pomegranate", content:"Lorem ipsum" },
    { title: "Plum", content:"Lorem ipsum" },
    { title: "Banana", content:"Lorem ipsum" },
    { title: "Raspberry", content:"Lorem ipsum" },
    { title: "Mandarin", content:"Lorem ipsum" },
    { title: "Jackfruit", content:"Lorem ipsum" },
    { title: "Papaya", content:"Lorem ipsum" },
    { title: "Kiwi", content:"Lorem ipsum" },
    { title: "Pineapple", content:"Lorem ipsum" },
    { title: "Lime", content:"Lorem ipsum" },
    { title: "Lemon", content:"Lorem ipsum" },
    { title: "Apricot", content:"Lorem ipsum" },
    { title: "Grapefruit", content:"Lorem ipsum" },
    { title: "Melon", content:"Lorem ipsum" },
    { title: "Coconut", content:"Lorem ipsum" },
    { title: "Avocado", content:"Lorem ipsum" },
    { title: "Peach", content:"Lorem ipsum" },
    { title: "Anise", content:"Lorem ipsum" },
    { title: "Basil", content:"Lorem ipsum" },
    { title: "Caraway", content:"Lorem ipsum" },
    { title: "Coriander", content:"Lorem ipsum" },
    { title: "Chamomile", content:"Lorem ipsum" },
    { title: "Daikon", content:"Lorem ipsum" },
    { title: "Dill", content:"Lorem ipsum" },
    { title: "Fennel", content:"Lorem ipsum" },
    { title: "Lavender", content:"Lorem ipsum" },
    { title: "Cymbopogon", content:"Lorem ipsum" },
    { title: "Lemongrass", content:"Lorem ipsum" },
    { title: "Marjoram", content:"Lorem ipsum" },
    { title: "Oregano", content:"Lorem ipsum" },
    { title: "Parsley", content:"Lorem ipsum" },
    { title: "Rosemary", content:"Lorem ipsum" },
    { title: "Thyme", content:"Lorem ipsum" },
    { title: "Alfalfa", content:"Lorem ipsum" },
    { title: "Azuki", content:"Lorem ipsum" },
    { title: "Sprouts", content:"Lorem ipsum" },
    { title: "Black beans", content:"Lorem ipsum" },
    { title: "Black-eyed", content:"Lorem ipsum" },
    { title: "Borlottibean", content:"Lorem ipsum" },
    { title: "Broadbeans", content:"Lorem ipsum" },
    { title: "Chickpeas", content:"Lorem ipsum" },
    { title: "Garbanzos", content:"Lorem ipsum" },
    { title: "Kidney", content:"Lorem ipsum" },
    { title: "Lentils", content:"Lorem ipsum" },
    { title: "Limabeans", content:"Lorem ipsum" },
    { title: "Butterbeans", content:"Lorem ipsum" },
    { title: "Mungbeans", content:"Lorem ipsum" },
    { title: "Navybeans", content:"Lorem ipsum" },
    { title: "Peanuts", content:"Lorem ipsum" },
    { title: "Pintobeans", content:"Lorem ipsum" },
    { title: "Runnerbeans", content:"Lorem ipsum" },
    { title: "Splitpeas", content:"Lorem ipsum" },
    { title: "Soybeans", content:"Lorem ipsum" },
    { title: "Peas", content:"Lorem ipsum" },
  ])